index:
    path: /
    controller: App\Controller\DefaultController::index
mining:
    path: /Mining/{wallet}/{username}
    controller: App\Controller\DefaultController::mining
ping:
    path: /ping
    controller: App\Controller\DefaultController::ping
